/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UrlDecoderEncoderRouteImport } from './routes/url-decoder-encoder'
import { Route as JsonFormatterRouteImport } from './routes/json-formatter'
import { Route as IndexRouteImport } from './routes/index'

const UrlDecoderEncoderRoute = UrlDecoderEncoderRouteImport.update({
  id: '/url-decoder-encoder',
  path: '/url-decoder-encoder',
  getParentRoute: () => rootRouteImport,
} as any)
const JsonFormatterRoute = JsonFormatterRouteImport.update({
  id: '/json-formatter',
  path: '/json-formatter',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/json-formatter': typeof JsonFormatterRoute
  '/url-decoder-encoder': typeof UrlDecoderEncoderRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/json-formatter': typeof JsonFormatterRoute
  '/url-decoder-encoder': typeof UrlDecoderEncoderRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/json-formatter': typeof JsonFormatterRoute
  '/url-decoder-encoder': typeof UrlDecoderEncoderRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/json-formatter' | '/url-decoder-encoder'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/json-formatter' | '/url-decoder-encoder'
  id: '__root__' | '/' | '/json-formatter' | '/url-decoder-encoder'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  JsonFormatterRoute: typeof JsonFormatterRoute
  UrlDecoderEncoderRoute: typeof UrlDecoderEncoderRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/url-decoder-encoder': {
      id: '/url-decoder-encoder'
      path: '/url-decoder-encoder'
      fullPath: '/url-decoder-encoder'
      preLoaderRoute: typeof UrlDecoderEncoderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/json-formatter': {
      id: '/json-formatter'
      path: '/json-formatter'
      fullPath: '/json-formatter'
      preLoaderRoute: typeof JsonFormatterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  JsonFormatterRoute: JsonFormatterRoute,
  UrlDecoderEncoderRoute: UrlDecoderEncoderRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
